image: node:alpine

before_script:
  - export APP_ENV=testing
  - export PATH=$PATH:/usr/local/bin
  - export PATH=$PATH:~/.nvm/versions/node/v15.14.0/bin
#  - yarn config set registry 'https://registry.npm.taobao.org'
stages:
  - build
  - deploy

variables:
  NPM_CONFIG_CACHE: "/var/cache/npm"
  YARN_CACHE_FOLDER: "/var/cache/yarn"
  DOCKER_DRIVER: overlay2
build-package:
  stage: build
  dependencies: [ ]
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - node_modules
  script:
    - if [ ! -d "node_modules" ]; then
    - yarn install --cache-folder /cache/yarn
    - fi
    - yarn build:weapp
  artifacts:
    name: "wxpkg-dlkhgl-$CI_COMMIT_TAG"
    untracked: false
    paths:
      - dist
deploy:
  stage: deploy
  dependencies:
    - build-package
  variables:
    GIT_STRATEGY: none
  before_script: [ ]
  script:
    # 获取HTTP服务的端口, 该端口是不固定的
    #    - PORT=`cat ~/Library/Application\ Support/微信开发者工具/Default/.ide`
    # 调用上传的API
    #    - curl http://127.0.0.1:$PORT/upload\?projectpath\=$PWD/dist\&version\=$CI_COMMIT_TAG\&desc\=audo-deploy
    # 以下改用命令行替代旧的 HTTP 调用方式（这种方式不支持 docker）
    - /Applications/wechatwebdevtools.app/Contents/MacOS/cli -u $CI_COMMIT_TAG@/$PWD/dist --upload-desc "aoto deploy"

